name: Shopify Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lighthouse
      uses: shopify/lighthouse-ci-action@v1
      with:
        access_token: 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
        store: test12345678064.myshopify.com
        password: down
	      lhci_github_app_token: f0ICUHa3ErqF9Ou:27640744:xDdrmiY5m